#ifndef _BOOKWORM_TVREMOTE_H_
#define _BOOKWORM_TVREMOTE_H_

#include <Arduino.h>

enum
{
	TVREMOTE_KEY_UNKNOWN = -1,
	TVREMOTE_KEY_NONE = 0,
	TVREMOTE_KEY_POWER,
	TVREMOTE_KEY_MUTE,
	TVREMOTE_KEY_VOLUMEUP,
	TVREMOTE_KEY_VOLUMEDOWN,
	TVREMOTE_KEY_CHANNELUP,
	TVREMOTE_KEY_CHANNELDOWN,
	TVREMOTE_KEY_0,
	TVREMOTE_KEY_1,
	TVREMOTE_KEY_2,
	TVREMOTE_KEY_3,
	TVREMOTE_KEY_4,
	TVREMOTE_KEY_5,
	TVREMOTE_KEY_6,
	TVREMOTE_KEY_7,
	TVREMOTE_KEY_8,
	TVREMOTE_KEY_9,
	TVREMOTE_KEY_SELECT,
	TVREMOTE_KEY_UP,
	TVREMOTE_KEY_DOWN,
	TVREMOTE_KEY_LEFT,
	TVREMOTE_KEY_RIGHT,
	TVREMOTE_KEY_PLAY,
	TVREMOTE_KEY_STOP,
	TVREMOTE_KEY_PREV,
	TVREMOTE_KEY_NEXT,
	TVREMOTE_KEY_INFO,
	TVREMOTE_KEY_GUIDE,
	TVREMOTE_KEY_MENU,
	TVREMOTE_KEY_JUMP,
	TVREMOTE_KEY_YELLOW,
	TVREMOTE_KEY_BLUE,
	TVREMOTE_KEY_RED,
	TVREMOTE_KEY_GREEN,
	//TVREMOTE_KEY_REPEATLAST,
};

enum
{
	TVREMOTE_BRAND_UNKNOWN      = -1,
	TVREMOTE_BRAND_UNUSED       =  0,
	TVREMOTE_BRAND_RC5,
	TVREMOTE_BRAND_RC6,
	TVREMOTE_BRAND_NEC,
	TVREMOTE_BRAND_SONY,
	TVREMOTE_BRAND_PANASONIC,
	TVREMOTE_BRAND_JVC,
	TVREMOTE_BRAND_SAMSUNG,
	TVREMOTE_BRAND_WHYNTER,
	TVREMOTE_BRAND_AIWA_RC_T501,
	TVREMOTE_BRAND_LG,
	TVREMOTE_BRAND_SANYO,
	TVREMOTE_BRAND_MITSUBISHI,
	TVREMOTE_BRAND_DISH,
	TVREMOTE_BRAND_SHARP,
	TVREMOTE_BRAND_DENON,
	TVREMOTE_BRAND_PRONTO,
	TVREMOTE_BRAND_LEGO_PF,
}; // this order matches "decode_type_t"

#endif